- name: add webupd8 ppa
  apt_repository: repo='ppa:webupd8team/java'

- name: update
  shell: apt-get update
  sudo: yes

- name: auto accept oracle jdk license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  sudo: yes

- name: install java8
  shell: apt-get install -y oracle-java8-installer ca-certificates
  sudo: yes

- name: Maven is downloaded
  	unarchive: http://apache-mirror.rbc.ru/pub/apache/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz dest=/home/vagrant/ copy=no
